<a href="https://colab.research.google.com/github/Akanksha-Ceris/Pandas_practice/blob/main/Pandas_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas  as pd
runs = [23,56,78]
pd.Series(runs)

0    23
1    56
2    78
dtype: int64

In [ ]:
# custom index
marks = [45,67,89]
subjects =['math','englis','hindi']
pd.Series(marks,index=subjects)

math      45
englis    67
hindi     89
dtype: int64

In [ ]:
# customer code
marks = [34,56,78]
subjects =['maths','englsh','science']
pd.Series(marks,index=subjects)

maths      34
englsh     56
science    78
dtype: int64

In [ ]:
# setting a name
marks = pd.Series(marks,index = subjects,name = 'Nitish ke marks' )
print(marks)

maths      34
englsh     56
science    78
Name: Nitish ke marks, dtype: int64

Series from dict

In [ ]:
marks = {
    'maths':67,
    'english':57,
    'science':89,
    'hindi':100
}
marks_series = pd.Series(marks,name ='akanksha ke marks')
marks_series

maths       67
english     57
science     89
hindi      100
Name: akanksha ke marks, dtype: int64

Series Attributes

In [ ]:
# size
marks_series
{ 'maths':67,'english':57,'science': 89,'hindi':100}
print(marks_series.size)

4

In [ ]:
#dtype
marks_series.dtype

dtype('int64')

In [ ]:
# name
marks_series.name

'akanksha ke marks'

In [ ]:
# is_unique
marks_series.is_unique
pd.Series([1,2,1,3,5]).is_unique

False

In [ ]:
#index
marks_series.index

Index(['maths', 'english', 'science', 'hindi'], dtype='object')

In [ ]:
# values
marks_series.values

array([ 67,  57,  89, 100])

# New Section