<a href="https://colab.research.google.com/github/Akanksha-Ceris/Pandas_practice/blob/main/Pandas_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas  as pd
runs = [23,56,78]
pd.Series(runs)

0    23
1    56
2    78
dtype: int64

In [ ]:
# custom index
marks = [45,67,89]
subjects =['math','englis','hindi']
pd.Series(marks,index=subjects)

math      45
englis    67
hindi     89
dtype: int64

In [ ]:
# customer code
marks = [34,56,78]
subjects =['maths','englsh','science']
pd.Series(marks,index=subjects)

maths      34
englsh     56
science    78
dtype: int64

In [ ]:
# setting a name
marks = pd.Series(marks,index = subjects,name = 'Nitish ke marks' )
print(marks)

maths      34
englsh     56
science    78
Name: Nitish ke marks, dtype: int64

Series from dict

In [ ]:
marks = {
    'maths':67,
    'english':57,
    'science':89,
    'hindi':100
}
marks_series = pd.Series(marks,name ='akanksha ke marks')
marks_series

maths       67
english     57
science     89
hindi      100
Name: akanksha ke marks, dtype: int64

Series Attributes

In [ ]:
# size
marks_series
{ 'maths':67,'english':57,'science': 89,'hindi':100}
print(marks_series.size)

4

In [ ]:
#dtype
marks_series.dtype

dtype('int64')

In [ ]:
# name
marks_series.name

'akanksha ke marks'

In [ ]:
# is_unique
marks_series.is_unique
pd.Series([1,2,1,3,5]).is_unique

False

In [ ]:
#index
marks_series.index

Index(['maths', 'english', 'science', 'hindi'], dtype='object')

In [ ]:
# values
marks_series.values

array([ 67,  57,  89, 100])

# New Section

In [ ]:
import pandas
mydataset = {
    'cars' :["BMW","VOLVO","FORD"],
    'passigns':[3,7,2]

}
myvar = pandas.DataFrame(mydataset)
print(myvar)

    cars  passigns
0    BMW         3
1  VOLVO         7
2   FORD         2

In [ ]:
import pandas as pd

In [ ]:

mydataset = {
    'cars':["BMV","VOLVO","FORD"],
    'passings':[3,7,2]

}
myvar = pd.DataFrame(mydataset)
print(myvar)

    cars  passings
0    BMV         3
1  VOLVO         7
2   FORD         2

In [ ]:
#  date is 5 of march 2026
# crate a simple pandas as pd
import pandas as pd
a = [1,7,2]
myvar = pd.Series(a)
print(myvar)

0    1
1    7
2    2
dtype: int64

In [ ]:
# return the first value of the Series
print(myvar[0])

1

In [ ]:
# create your own labels:
a = [1,7,2]
myvar = pd.Series(a,index = ["x","y","z"])
print(myvar)

x    1
y    7
z    2
dtype: int64

In [ ]:
# when you have created labels , you can access an item by referring to the label
# example:
# return  the value of "y"
print(myvar["y"])

7

 key/Values Objects as Series

In [ ]:
# create a  simple pandas Series from a dictonary:
calories = {"day1":345,"day2":789,"day3":783}
myvar = pd.Series(calories)
print(myvar)
# here the keys of the dictionary become the labels

day1    345
day2    789
day3    783
dtype: int64

In [ ]:
# create  a Series using only data from "day1" and "day2":

myvar = pd.Series(calories,index=["day1","day2"])
print(myvar)

day1    345
day2    789
dtype: int64

DataFrames

Data sets in pandas are usually multi-dimensional tables ,called Dataframes
series is like a column , a DataFrame is the whole table

In [ ]:
# create a Dataframe from  two series
data = {
    "calories":[234,56,789],
    "duration":[50,40,45]
}
myvar = pd.DataFrame(data)
print(myvar)

   calories  duration
0       234        50
1        56        40
2       789        45

Locate Row

What is Dataframe?
A pandas Dataframe is a 2 dimensional data structure ,like a 2 dimensional array, or a table with rows and columns.

In [ ]:
# Create a simple Pandas Dataframe
data = {
    "colories":[789,34,56],
    "duration":[56,34,56]

    }
    #load data into a Dataframe objects:
df = pd.DataFrame(data)
print(df)

   colories  duration
0       789        56
1        34        34
2        56        56

In [ ]:
# use a list of indexes:
print(df.loc[[0,1]])

   colories  duration
0       789        56
1        34        34

# Named Indexes

In [ ]:
# with the index argunment , you can  name your own indexes
# Add a list of names to give each row a name:
data = {
    "calories":[420,380,390],
    "duration":[50,40,45]
}
df = pd.DataFrame(data,index=["day1","day2","day3"])
print(df)

      calories  duration
day1       420        50
day2       380        40
day3       390        45

Locate

Load Files into a DataFrame
If your data sets are stored in a file, Pandas can load them into  a DataFRame

In [ ]:
# Load a comma deparated file(CSV file ) into a Dataframe

In [3]:
import pandas as pd

Series using read_csv

In [4]:
# with one col

Series using read_csv

In [14]:
# with one col
subs=pd.read_csv('/content/subs.csv').squeeze("columns")
subs

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [16]:
# with 2 cols
vk =pd.read_csv('/content/kohli_ipl.csv',index_col='match_no').squeeze("columns")
print(vk)

match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64

Series methods

In [17]:
# head and tail
# it provide top 5 rows of dataseet
subs.head()

0    48
1    57
2    40
3    43
4    44
Name: Subscribers gained, dtype: int64

In [18]:
vk.head(3)

match_no
1     1
2    23
3    13
Name: runs, dtype: int64

In [19]:
# Tail
vk.tail()

match_no
211     0
212    20
213    73
214    25
215     7
Name: runs, dtype: int64

In [20]:
# it provide last 10 matches of ipl
vk.tail(10)

match_no
206     0
207     0
208     9
209    58
210    30
211     0
212    20
213    73
214    25
215     7
Name: runs, dtype: int64

In [22]:
# sample. it select  columns randomly
vk.sample()

match_no
63    45
Name: runs, dtype: int64

In [23]:
# show randomly 5 columns from the dataset
vk.sample(5)

match_no
208     9
173    29
103    51
35      3
131    54
Name: runs, dtype: int64

In [26]:
# value counts
cars=pd.read_csv('/content/cars.csv')
cars

        brand  km_driven    fuel                 owner  selling_price
0      Maruti     145500  Diesel           First Owner         450000
1       Skoda     120000  Diesel          Second Owner         370000
2       Honda     140000  Petrol           Third Owner         158000
3     Hyundai     127000  Diesel           First Owner         225000
4      Maruti     120000  Petrol           First Owner         130000
...       ...        ...     ...                   ...            ...
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

[8128 rows x 5 columns]

In [28]:
vk.value_counts()

runs
0     9
1     8
12    8
9     7
8     6
     ..
46    1
29    1
84    1
90    1
53    1
Name: count, Length: 78, dtype: int64

In [33]:
# sort values4# method chaning
vk.sort_values(ascending = False).head(1).values[0]

np.int64(113)

In [36]:
cars.sort_index()

        brand  km_driven    fuel                 owner  selling_price
0      Maruti     145500  Diesel           First Owner         450000
1       Skoda     120000  Diesel          Second Owner         370000
2       Honda     140000  Petrol           Third Owner         158000
3     Hyundai     127000  Diesel           First Owner         225000
4      Maruti     120000  Petrol           First Owner         130000
...       ...        ...     ...                   ...            ...
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

[8128 rows x 5 columns]

In [39]:
# sort_index -> inplace -> movies
cars.sort_index(inplace = True)
cars

        brand  km_driven    fuel                 owner  selling_price
0      Maruti     145500  Diesel           First Owner         450000
1       Skoda     120000  Diesel          Second Owner         370000
2       Honda     140000  Petrol           Third Owner         158000
3     Hyundai     127000  Diesel           First Owner         225000
4      Maruti     120000  Petrol           First Owner         130000
...       ...        ...     ...                   ...            ...
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

[8128 rows x 5 columns]